filebeat.inputs:
- type: container
  paths: 
    - "/var/lib/docker/containers/*/*.log"

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

output.logstash:
  hosts: ["logstash:5044"]
